services:
  db:
    image: docker.io/library/postgres:15.3-bullseye                                 # postgres version get from dockerhub
    container_name: scrap_db                                                         # container name : your_choice for create a space 
    init: true                                                                      # container initialization
    env_file:                                                                       # Env configurations
      - .env
    restart: always                                                                 #changes reflicting
    volumes:                                                                        #mount local storage to container
      - pg_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'                                     #command :run packages postgres- c :run command max_coonection:1000
    ports:                                                                          # port change
      - "9008:5432"
    networks:                                                             # Group all containers in the single network for relation b/w containers
      - net
    logging:
      options:
        max-size: 1000m

  api_base:
    image: scrap_api:0.0.1
    container_name: scrap_local
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile 
    init: true
    env_file: 
      - .env
    restart: always
    volumes :
      - .:/app
    command: sleep infinity
    networks:
      - net
   
  scrap_api:
    extends:
      service: api_base
    container_name: scrap_api
    command: python manage.py runserver 0.0.0:8000
    ports:
      - "8001:8000"
  
  scrap_links:  
    extends:
      service: api_base
    container_name: scrap_links
    command: python -u manage.py runscript run

  pgadmin: #postgresql UIs
    image: dpage/pgadmin4:8.14
    container_name: scrap_pg
    init: true
    env_file:
      - .env
    restart: always
    volumes:
      - pgadmin_local:/var/lib/pgadmin
    ports:
      - 9006:80
    networks:
      - net
    logging:
      options:
        max-size: 1000m

networks:
  net:
    name: scrap_net
    external: false

volumes:
  pg_data: {}
  pgadmin_local: {}